### ISSUE TITLE
[Bug] Gemini

### ISSUE THREAD

**Issue by non-bin** [OnewheelCommunityEdition/OWCE_App#107]
I have a 5314 pint, I updated to 5100 because I was curious, and now the app doesn't show cell voltage, total voltage, or current :(
Is this just another FFM thing? any idea how to downgrade? FFMWheel times out while trying to flash (https://github.com/ffmwheel/rewheel-main/issues/3)

**Comment by beeradmoore** [comment]
Hey @non-bin,
Yeah, unfortunately FM removed that functionality for many of the firmware overtime. Kinda disappointing removing something that people can use to monitor their boards health.

Sorry I can't provide any support for ffmwheel or comment on firmware downgrade methods.

On the positive side, if I come across anyway to enable that data for you from within the OWCE app without any board modifications I'll be sure to add it in.
