### ISSUE TITLE
Pint + XR fw4210 support

### ISSUE THREAD

**Issue by beeradmoore** [OnewheelCommunityEdition/OWCE_App#37]
This is functional, but still a work in progress as to not get you on a bad watchlist. 

See [this](https://github.com/ponewheel/android-ponewheel/issues/109) thread for more details.

**Comment by thibauddavid** [comment]
Hey @beeradmoore , author of [OnewheelEnhancer](https://github.com/thibauddavid/onewheelenhancer-issues) here. As you seem to have begun working on pint/>4210 support, maybe you'd time to dig into this https://github.com/thibauddavid/onewheelenhancer-issues/issues/3. 

Basically, cells voltage bluetooth characteristic data changed on >4210.
For what I've found, bytes[0].high4 now represents cell's number (vs entire byte before), and last byte represent cell's voltage (as before). Don't know what bytes[0].low4 is for, seem to always be `e`
- Eg before: 0x029c (cell 2, 3.12V)
- Eg >4210: 0x2e9c (cell 2, 3.12V)

But on the issue above, @git-cbri who had correct values on first log file he provided, now has much lower voltage (~2.42V), while still having a normal battery voltage. Seems like FM did some kind of encoding here, but couldn't find a pattern yet.

If you already checked this, I'm open :)

**Comment by beeradmoore** [comment]
@thibauddavid , does that mean the other byte is useless now? Previously it had cell ID in it. 

I do recall when I had OWCE connecting to my Pint that it would give odd behaviour for better cells. It would essentially just keep looping and adding new cells, like cell ID 100, 200, 220, etc. I don't recall if that was because of a bug or something to do with the data I never realised.

But thinking about this with this new info, I think this may have been what cause the issue. I never looked further into it and Pint/XR was dropped until I setup the OWCE Web API to handle new board connections. 

Would be nice if they are sending two cell ID+Values in the one two byte payload.

**Comment by thibauddavid** [comment]
That's exactly the problem I had, app reading weird cells number (eg: 148, 158...).
But by taking only the first nibble, you will get cell number on >4210 & pint. Second nibble seems useless (always to "e"), and second byte is voltage as usual, but with some king of encoding.

> Would be nice if they are sending two cell ID+Values in the one two byte payload.

Don't think it's possible, 2 bytes is not enough to represent 2 cells number + 2 voltages

I've disassemble iOS app, I'll dive into it soon to find how that works, I'll keep you in touch.

**Comment by beeradmoore** [comment]
Probably unrelated but my first thought of `e` is similar to watching the serial output. When converted to string it outputs "One " (or was it Onew) a lot.

Good work, I'll get some more time with OWCE this weekend. Currently doing a different overhaul, but I'll re-enable Pint support and see what I can make of these battery voltages.

**Comment by beeradmoore** [comment]
@thibauddavid , turns out they changed how cell voltages are cent for Pint and XR with HW >4210. Previously it was first byte is cell ID, second byte is cell voltage. This has now changed to be first 4 bits being cell ID, and remaining 12 bits being cell voltage. There is also some new math around converting cell voltages from value to float value, you can see that below. As a plus we now have better resolution for cell voltages.

This is the code I just added to OWCE.

```
// Different battery cell logic for XR 4210+ and Pint.
if (_firmwareRevision.Value >= 4141)
{
    var cellID = (uint)((value & 0xF000) >> 12);
    var batteryVoltage = (value & 0x0FFF) * 0.0011f;
    _batteryCells.SetCell(cellID, batteryVoltage, "F3");
}
else
{
    var cellID = (uint)data[1];
    var batteryVoltage = (float)data[0] * 0.02f;
    _batteryCells.SetCell(cellID, batteryVoltage);
}
```

**Comment by thibauddavid** [comment]
Good to know thanks ! Didn’t had time to dive into official app asm so I
hijacked OWDataKeeper’s values instead so I let FM’s app do the hard work
instead :)

**Comment by Gigahawk** [comment]
@beeradmoore has that new battery logic been pushed anywhere?

I just got my Pint and would love to start helping out with this project.

**Comment by beeradmoore** [comment]
@Gigahawk , only pushed locally. It will all go public until the next version is pushed to testers. But that is awaiting me to finish the UI overhaul. I can ping you back in this thread when that is out in the wild though.

**Comment by LeeStevens318** [comment]
Any further update on this?

**Comment by beeradmoore** [comment]
This is now both pushed to development branch and released in the public beta.
