### ISSUE TITLE
[Bug] Android does not display battery cells

### ISSUE THREAD

**Issue by beeradmoore** [OnewheelCommunityEdition/OWCE_App#38]
**Describe the bug**
Just displays - - - - for each battery cell.

**To Reproduce**
1. Connect to board.
2. Hit info.
3. Wait for battery cells to load.

**Expected behavior**
Cells load.

**Screenshots**
N/A

**Phone (please complete the following information):**
 - OS: Android

**Onewheel (please complete the following information):**
All

**Comment by onewheelamo** [comment]
looks like this issue appeared again on android 11, phone is poco f2 pro runing MIUI global 12.5.1
OWCE build 66
onewheel hardware 4212
onewheel firmware 4155

same behavior as before, apps displays a dash instead of cells voltage

**Comment by onewheelamo** [comment]
issue does not appear on hw 4209 / fw 4134 on android may be a mislead from me there (sry)

**Comment by beeradmoore** [comment]
@onewheelamo from memory the issue you are seeing is that FM removed voltage data being removed from the board with firmware 4155 (maybe even 4150).

Are you able to confirm there is no voltage information displayed in the diagnostics screen when using the stock OW app?

**Comment by onewheelamo** [comment]
@beeradmoore i can totaly confirm there is no voltage info on the diagnostics screen, would you need a screenshot ?

**Comment by beeradmoore** [comment]
Nope, no screenshot required. Just confirming.

So FM removed the feature from the board where it sends voltage to the app (I presume to try make after market battery mods less useful). As a result OWCE can't read battery voltage or individual cells until a possible workaround has been found, but so far nada.

I should probably add a warning so people know why there is no voltage for them.
