### ISSUE TITLE
Current draw displaying raw data and value seems to fluctuate wildly

### ISSUE THREAD

**Issue by BlakeWard** [OnewheelCommunityEdition/OWCE_App#46]
I was watching the current power draw value while riding my board and it seemed to jump around wildly between 6500 and 2.  I was going at a steady (low) speed on the flats, so would have expected it to be fairly steady.  Not sure whether this is a bug in the app or just a problem  with the value reported by the board.

(I wanted to look at that value because I was curious if it might be a better indicator than speed for when a nosedive might be imminent.)

**Comment by beeradmoore** [comment]
I don't think current draw is converted to displaying a useable number, so its just displaying raw value from the board. 

I'd like to add in some diagnostics recording so I can log all this stuff to a file to replay it through the app to see if we are converting all the numbers right.

And yeah, I've thought power draw would be a much better indicator of nosedive than speed. It ironically was the whole reason OWCE exists, to find more reason why and to give better warnings for nosedives :P  

I'm just going to edit the title of this and add it to the road map. Thanks for filing an issue!

**Comment by beeradmoore** [comment]
I've fixed this locally to display correct number. But I am interestingly still seeing high numbers when I accelerate hard. I assume my board is not actually pulling 120A from the battery.

**Comment by beeradmoore** [comment]
This has now been resolved. Thanks for bringing it up @BlakeWard
