### ISSUE TITLE
[Feature Request] Migrating away from syncfusion?

### ISSUE THREAD

**Issue by Gigahawk** [OnewheelCommunityEdition/OWCE_App#49]
**Is your feature request related to a problem? Please describe.**
I registered for a syncfusion account a while ago and got endlessly pestered by them over email.

When I finally responded that I was using the key for this project this was the response I got:

> I have checked in with our legal team. Unfortunately, we do not allow our products to be used in GPL or copyleft products. I have cc’d in our counsel and she is happy to discuss it further.

**Describe the solution you'd like**
I'm not too familiar with Xamarin, but surely there are other open source libraries we could be using to display the graphs in the app

**Comment by beeradmoore** [comment]
That is interesting, the Syncfusion license we use for builds is specifically the community license for open source projects. They had to come and view our project before they granted the license. 🤔 I'll look into this more when I'm available.

Dropping Syncfusion isn't so bad anymore. It used to be the main dial for the speedometer. But in new design (not pushed public anywhere yet) we dropped that requirement but were still keeping it around for future use of displaying graphs of battery usage over time etc. 

There are some other graphing libraries to use, Telerik is one off the top of my head. Having used it to work and constantly requesting can we please move away from it, I wouldn't put it in my top list to choose from. 

The graphs we want are not overly complex so we could even just draw them with native iOS/Android drawing methods, or us some of the [new path components](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/polyline) of Xamarin.Forms directly. We lose the ability to pinch/pull/pan as we would have in Syncufsion. But again, for our purposes it could be an ok tradeoff.

EDIT: I should add, it is a bit of a pain point to expect people to get a license key to deploy locally and not be pestered by popups. So moving away from it does allow anyone to pull and deploy much quicker.

**Comment by Gigahawk** [comment]
Just letting you know they keep pestering me, and that I have a feeling this project should remove any mentions of syncfusion soon.

Not sure what they think people will use "Free Community" licenses for, but apparently free community projects do not fall under the list of valid use cases
![benstopbotheringme](https://user-images.githubusercontent.com/10356230/90950508-094a7500-e407-11ea-8293-8d3ab5b96dfe.png)

Apologies for the crappy pic, just getting a screenshot of the whole email was kinda annoying

**Comment by beeradmoore** [comment]
Eh, just tell them you were evaluating it for another project you had found. Feel free to link to this repo. If they want to contact me regarding it they can and will. As I said, they literally had to come look at the project to approve it in the first place.

Next build will remove syncfusion for the time being. At some point I'll double check the licenses they are compatible with and see if its compatible with this project if we were to re-license.

Their library is great for graphs so I would still love to use it, but if it doesn't work in future I'll happily move on from them. UI overhaul + public release is the main priority.

Thanks again for bringing this to my attention though.

**Comment by Gigahawk** [comment]
This repo is linked in the bottom half of that screenshot (again apologies for the crappy pic).

My guess is this is some lazy oversight by a legal guy if theyve previously explicitly allowed it, but it's not a great experience for anyone who wants to build from source or help with development.

EDIT: went back and redid the license request process, requiring a LinkedIn/XING account is pretty awful lol
EDIT2: Just checked my LinkedIn, their whole privacy thing about not stalking your account is BS, the guy emailing me definitely stalked my page

**Comment by beeradmoore** [comment]
Agreed. I'll keep that in mind for the next project at work going forwards.

**Comment by beeradmoore** [comment]
Development branch no longer uses syncfusion.
