### ISSUE TITLE
[Feature Request] allow to select a top speed

### ISSUE THREAD

**Issue by dave-chk** [OnewheelCommunityEdition/OWCE_App#64]
In many europe countries, monowheel vehicles need the possibility to set a speed limit to the vehicle in order to make it legal on public places.
Currently the only way to have a speed limit is to use sequoia mode, which has a 12 mph limit.
The ability to set a different, arbitrary limit that works in the same way (i.e. 6kmh for italy) would be of great help.
Limit can be added or removed as a custom usage mode.

**Comment by beeradmoore** [comment]
Hey @dave-chk ,
Unfortunately it is not possible to impose a speed limit without modifying the board firmware (which is pretty much impossible).

We can have an alarm for when you hit a speed limit if that helps at all?

**Comment by dave-chk** [comment]
Thanks for the quick answer!Oh I didn't imagine that firmware was involved, I hoped that it was something related to profiles but not hard coded in firmware.
An alert on a particular speed limit might help, but probably won't do on a legal point of view, so I'd say that it is worth depending on the number of requests and the difficulty to implement it.

Thanks again :) and keep up with the good work with the app!

    On Friday, August 13, 2021, 12:59:29 AM GMT+2, Brad ***@***.***> wrote:  
 
 


Hey @dave-chk ,
Unfortunately it is not possible to impose a speed limit without modifying the board firmware (which is pretty much impossible).

We can have an alarm for when you hit a speed limit if that helps at all?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beeradmoore** [comment]
100% agree on changing the legality. As for speed alert we have an open issue for that (#42), so I am closing this in favour of that.  Thanks for the input!
