### ISSUE TITLE
[Bug]  Possible Android 12 incompatibility? 

### ISSUE THREAD

**Issue by trappedinalift** [OnewheelCommunityEdition/OWCE_App#76]
**Describe the bug**
OWCE stuck at scanning and doesn't find board. Worked as intended on my Android 10 phone, updating to Android 12 causes OWCE to no longer work. Downgrade to Android 10, OWCE works again.

**Phone (please complete the following information):**
POCO X3 Android 12.1

**Onewheel (please complete the following information):**
Pint

**Comment by beeradmoore** [comment]
Hey, sorry I thought I responded to this.

Did this sort itself out?

**Comment by trappedinalift** [comment]
Hey, it was my own stupidity. Location needs to be on to enable Bluetooth scanning....

**Comment by beeradmoore** [comment]
If the app isn't checking and reminding you then it isn't your stupidity ;) 

Ill see what I can do to make this more clear in the future.
