### ISSUE TITLE
App does not compile

### ISSUE THREAD

**Issue by NeedNot** [OnewheelCommunityEdition/OWCE_App#78]
I have never used c# before only java and python so forgive me.

before I ever make any code changes I always compile it first to make sure everything is set up right.
i had no luck with the main branch or the development branch.

I was getting various errors including one where there was an extra closing } but I have forgotten which file that was in.
although the readme says to use vs 2017 is there any reason 2022 cannot work? i had vs 2019 already installed is so I used that and I was getting errors relating to just having outdated stuff so I switched to 2022 and most of the errors went away other than these 6

![Screenshot_1749](https://user-images.githubusercontent.com/47156725/183469124-3122e721-954e-48d1-90aa-0c67d1129502.png)

**Comment by NeedNot** [comment]
Im not really sure what happened but I connected to a faster internet and retried just 1 time on the main branch and it worked

**Comment by beeradmoore** [comment]
Hey @NeedNot ,
Readme is incorrect and should be updated. Recommended should be 2022. I've made a card to go fix that (#79). Thanks for bringing that to my attention. 

I'd also possibly recommend branching from development branch. I believe main is out of date slightly.
