### ISSUE TITLE
Onewheel battery operating "out of safety range" 

### ISSUE THREAD

**Issue by MikeNilsson** [OnewheelCommunityEdition/OWCE_App#80]
A major update on the OW (XR) was done recently and 150 miles went by with not issues. Now I am getting "out of safety range" message followed by OW will not operate afterwards. It has to be a safety feature but I really do not know how to fix it. This only happens when the weather is over 80 degrees.

When riding I will get below message and after stopping I cannot keep going since the OW will not engage. Shutdown and restart does not matter.

FMM chip removed and replaced with Owie. FMM made my OW nosediving on my with "error 22" messages. 
OWIE installed - working
JWXR installed - working

Original Hardware: 4212
New BMS:                    4209 (original 4212 got fried)
Firmwate:                     Gemini -4155

Battery indicates 32 Farenheit......clearly not reading &/or not working correctly.

I use a:
Iphone 12 pro
IOS 15.6

Any input would be mighty appreciated

![IMG_4021](https://user-images.githubusercontent.com/111311898/184716754-7992ff8c-27f0-4ca2-91d2-83a40610da70.PNG)

![IMG_4010 (1)](https://user-images.githubusercontent.com/111311898/184716781-8a707f67-04a3-42ef-89c6-607544d61caa.PNG)
.

**Comment by beeradmoore** [comment]
Hey @MikeNilsson,
I believe you may have posted to the wrong repo. This is OWCE (Onewheel Community Edition), a 3rd party app for Onewheels. I think you meant to post this over to OWIE (https://github.com/lolwheel/Owie) repo.

What I can tell you though is the battery reading 32F means it is reading 0C. Battery thermal sensor isn't working. Unsure what the cause could be, if its damaged cable, faulty sensor, etc.

**Comment by MikeNilsson** [comment]
Thank you Brad!

I posted where you indicated!

Best regards,

Mike Nilsson
360 Wicked Photography
+1 (425) 622-8230
www.360wickedphotography.com/
