### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by mcmurray** [OnewheelCommunityEdition/OWCE_App#81]
I am an idiot so please excuse me for beign and idiot and asking is this project dead?

I have been looking forward to the battery % by voltage feature for so long now and it doesnt appear there has been an update for nearly one year?

**Comment by beeradmoore** [comment]
Not dead. Been actively working on the ride recording update. But as you can see the progress is slow.

We need the ride recording update to get data to correctly implement the battery % update.
