### ISSUE TITLE
[Bug] OWCE App on iOS reports build removed

### ISSUE THREAD

**Issue by HyperKids** [OnewheelCommunityEdition/OWCE_App#90]
**Describe the bug**

**To Reproduce**
1. Open TestFlight (or attempt to launch OWCE app) on iOS

**Expected behavior**
The app should work.

**Screenshots**
N/A

**Phone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 16.0 (20A362)
 - Version (unknown)

**Onewheel (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by beeradmoore** [comment]
EDIT: latest update didn't roll out to everyone, this should now be fixed. Please check for an update in TestFlight to get build number 131


Any other info to go on here...
Did you get the required update from a few days ago from TestFlight?
Is it crashing?
Is it giving you an error?
Is it not detecting your board?

**Comment by HyperKids** [comment]
Hi - I am not aware of a required update from TestFlight. Two other app users have independently verified that it also shows "Build Removed" or "Build Expired" for them on TestFlight.
![image](https://user-images.githubusercontent.com/12666237/215238257-b54496a4-5903-4233-94b0-c623dac606fd.jpeg)

**Comment by HyperKids** [comment]
Thanks for re-pushing the update! Works now :)

**Comment by beeradmoore** [comment]
No worries, thanks for bringing it to my attention
